# Generated by Django 5.2.7 on 2025-10-23 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0001_initial'),
        ('productos', '0002_producto_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='cliente',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='detalquiler',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='detalquiler',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto'),
        ),
    ]
