# Generated by Django 5.2.7 on 2025-10-22 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alquileres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_incidente', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True)),
                ('estado_incidente', models.CharField(choices=[('abierto', 'Abierto'), ('resuelto', 'Resuelto'), ('anulado', 'Anulado')], default='abierto', max_length=10)),
                ('det_alquiler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to='alquileres.detalquiler')),
            ],
            options={
                'ordering': ['-fecha_incidente'],
            },
        ),
    ]
