# Generated by Django 5.2.7 on 2025-10-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='cantidad_afectada',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='incidente',
            name='cantidad_repuesta',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incidente',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidente',
            name='resultado_final',
            field=models.CharField(choices=[('sin_accion', 'Sin acción (no vuelve)'), ('reintegrado', 'Reintegrado al stock (reparado)'), ('repuesto', 'Repuesto por compra/alta')], default='sin_accion', max_length=20),
        ),
        migrations.AddField(
            model_name='incidente',
            name='tipo_incidente',
            field=models.CharField(choices=[('irreparable', 'Daño irreparable (rotura, pérdida)'), ('reparable', 'Daño reparable (suciedad, arreglo)')], default='reparable', max_length=12),
        ),
    ]
