# Generated by Django 5.2.7 on 2025-10-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('chofer', 'Chofer'), ('operario_carga', 'Operario de Carga y Descarga'), ('encargado', 'Encargado'), ('limpieza', 'Personal de Limpieza'), ('lavanderia', 'Operaria de Lavandería'), ('cajero', 'Cajero')], default='empleado', max_length=20),
        ),
    ]
