# Generated by Django 5.2.7 on 2025-10-23 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_perfil_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('empleado', 'Empleado'), ('chofer', 'Chofer'), ('operario_carga', 'Operario de Carga y Descarga'), ('encargado', 'Encargado'), ('limpieza', 'Personal de Limpieza'), ('lavanderia', 'Operaria de Lavandería'), ('cajero', 'Cajero')], default='empleado', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
