# Generated by Django 5.2.7 on 2025-10-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('vajilla', 'Vajilla'), ('cristaleria', 'Cristalería'), ('manteleria', 'Mantelería'), ('decoracion', 'Decoración'), ('salon', 'Salón'), ('mobiliario', 'Mobiliario')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('imagen_url', models.URLField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
